services:
  app_service:
    build: ./app
    container_name: app_service_docker
    environment:
      - OLLAMA_PORT=$OLLAMA_PORT
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                    
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - 5000:$APP_PORT
  llm_service:
    build: ./llm
    container_name: llm_service_docker
    volumes:
      - ./ollama:/ollama
    ports:
      - 11434:$OLLAMA_PORT
    environment:
      - OLLAMA_KEEP_ALIVE=-1