services:
  app_service:
    build: ./app
    container_name: app_service_docker
    environment:
      - OLLAMA_PORT=$OLLAMA_PORT
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                    
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - $APP_PORT:5000
  llm_service:
    build: ./llm
    container_name: llm_service_docker
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - $OLLAMA_PORT:11434
    environment:
      - OLLAMA_KEEP_ALIVE=-1