services:
  app_service:
    build: ./app
    container_name: app_service_docker
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                    
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
  llm_service:
    build: ./llm
    container_name: llm_service_docker
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: -1